---
title: "interactive-contact-conversion"
author: "Dan Spakowicz"
date: "12/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Read in data

Data must be exported in OUTLOOK format

```{r read in google contacts export, message=FALSE}
x <- read_csv("../data/2023-12-10_contacts.csv")

head(x)

```

```{r}
x %>%
  filter(is.na(`Home Address`))
```



Select columns of interest.

```{r}
# df <- 
#   x %>%
#   select(`First Name`, `Middle Name`, `Last Name`, `Home Street`, 
#           `Home City`, `Home State`, `Home Postal Code`) %>%
#   drop_na(`Home City`)

df <- 
  x %>%
  select(`First Name`, `Last Name`, `Home Street`,
          `Home City`, `Home State`, `Home Postal Code`) %>%
  drop_na(`Home City`)

head(df)
```

```{r}
# Create a new field for matching addresses (too many different Rd vs Rd. vs Road etc)
num.st <- strsplit(df$`Home Street`, split = " ")
df$num.st <- lapply(num.st, function(x) paste(x[1], x[2], sep = " ")) %>%
  unlist

# Split out the duplicates
dups <- duplicated(df$num.st)
dupsdf <- df[dups,]
out <- df[!dups,]

# For each duplicated contact
for (i in 1:nrow(dupsdf)) {
  
  # Find the matched contact in out
  check <- grep(dupsdf$num.st[i], out$num.st)
  
  # Are the last names the same?
  all.last.names <- unique(c(out$`Last Name`[check], dupsdf$`Last Name`[i]))
  if (length(all.last.names) == 1) {
    # Change the name to of the last of the duplicates to $FIRSTNAME1 & 
    # FIRSTNAME2 $LASTNAME
    firstnames <- c(out$`First Name`[check], dupsdf$`First Name`[i])
    out$`First Name`[check] <- paste(firstnames, collapse = " & ")
    out$`Last Name`[check] <- all.last.names
    
  } else {
    # If multiple last names, hyphenate
    out$`First Name`[check] <- paste(out$`First Name`[check], out$`Last Name`[check], 
                                   sep = " ")
    out$`Last Name`[check] <- paste("&", dupsdf$`First Name`[i], dupsdf$`Last Name`[i],
                                  sep = " ")
  }
} 

# Remove the num.st col used for matching
out$num.st <- NULL

```

```{r}
# Write output for uploading to website
date <- Sys.Date() %>%
  as.Date(format = "%F")
write.csv(out, file = paste0("../data/", date, "_holiday_simplytoimpress.csv", sep = ""),
            row.names = FALSE, na = "")
```

Tweaks for Shutterfly

```{r}
noHome <- function(x) gsub("Home (.*)", "\\1", x)

shut <- 
  out %>%
  mutate("Display/Household Name (Smith Family)" = "",
         "Address Line 2" = "",
         "Country" = "", 
         "Email" = "") %>%
  rename_at(c("Home City", "Home State", "Home Postal Code"),
            noHome) %>%
  rename("Address Line 1" = "Home Street") %>%
  select("First Name", "Last Name", "Display/Household Name (Smith Family)", "Address Line 1", "Address Line 2", "City", "State", "Postal Code", "Country", "Email")

head(shut)
```

```{r}
write.csv(shut, file = paste0(date, "_holiday_shutterfly.csv", sep = ""),
            row.names = FALSE, na = "")
```

# Tweaks for Paper Culture

```{r}
pc <-  
  out %>%
    mutate("Recipient Name (enter 1 per line)" = paste(`First Name`, `Last Name`, sep = " "),
           USAddress1 = `Home Street`,	
           USAddress2 = NA,
           USCity = `Home City`,
           USState	= state.name[match(`Home State`, state.abb)],
           USZipCode = `Home Postal Code`) %>%
  select(`Recipient Name (enter 1 per line)`, 
         USAddress1, 
         USAddress2, 
         USCity, 
         USState, 
         USZipCode)
  
write.csv(pc, file = paste0("../data/", date, "_holiday_paperculture.csv", sep = ""),
            row.names = FALSE, na = "")
```

state.name
```{r}
state.name
state.abb
match(out$`Home State`, state.)
```

